~/Workspace/General/:
  single_file_libs: git+git@github.com:nothings/single_file_libs.git
  stb: git+git@github.com:nothings/stb.git
  telegraf: git+git@github.com:influxdata/telegraf.git
  immer: git+git@github.com:arximboldi/immer.git
  tiny-dnn: git+git@github.com:tiny-dnn/tiny-dnn.git
  expressions-template-library: git+git@github.com:wichtounet/etl.git
  concurrentqueue: git+git@github.com:cameron314/concurrentqueue.git
  problem-solving: git+git@github.com:sangupta/ps.git

~/Workspace/Conferences/CppCon/:
  CppCon2014: git+git@github.com:CppCon/CppCon2014.git
  CppCon2015: git+git@github.com:CppCon/CppCon2015.git
  CppCon2016: git+git@github.com:CppCon/CppCon2016.git

~/Workspace/Private/GitHub/:
  dotfiles: git+git@github.com:ChristianWitts/dotfiles.git
  Dockerfiles: git+git@github.com:ChristianWitts/Dockerfiles.git
  glowing-couscous: git+git@github.com:ChristianWitts/glowing-couscous.git
  ChristianWitts.github.io: git+git@github.com:ChristianWitts/ChristianWitts.github.io.git
  nginx-service-generator: git+git@github.com:ChristianWitts/nginx-service-generator.git
  spamhaus: git+git@github.com:ChristianWitts/spamhaus.git
  UNIX-tools: git+git@github.com:ChristianWitts/UNIX-tools.git
  jump-commander: git+git@github.com:ChristianWitts/jump-commander.git
  gatewayd: git+git@github.com:ChristianWitts/gatewayd.git

~/Workspace/Languages/Rust:
  vndf: git+git@github.com:hannobraun/vndf.git
